apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-web # ИЗМЕНИТЕ: Укажите имя ConfigMap
  namespace: default # ОПЦИОНАЛЬНО: Укажите namespace, если не default
data:
  # КЛЮЧЕВОЙ МОМЕНТ: index.html будет подключен как файл
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Страница присоединяется из ConfigMap</title>
    </head>
    <body>
      <h1>Привет от Kubernetes! Группа FOPS-41 Муравский Артем</h1>
    </body>
    </html>
