apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}-backend
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
    instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
